# -*- coding: utf-8 -*-
"""pytest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10X1x29qUTeiMQLcAyQ1F7h5bf3KoNXWG
"""

#install Poetry

!curl -sSL https://install.python-poetry.org | python3 -
!export PATH=$PATH:~/.local/bin/
!poetry --version

!poetry new --src pygreet

import arrow

def greet(tz):
    """Greet a location with the current time."""
    now = arrow.now(tz)
    friendly_time = now.format("h:mm a")
    location = tz.split("/")[-1].replace("_", " ")
    return f"Hello, {location}! The time is {friendly_time}."

poetry add arrow

poetry install

[pygreet]$ poetry run python
>>> from greet.location import greet
>>> greet("Asia/Shanghai")
'Hello, Shanghai! The time is 4:05 am.'
>>>

[pygreet]$ poetry shell
Spawning shell within
~/.cache/pypoetry/virtualenvs/pygreet-abcd1234-py3.8
[pygreet]$ . ~/.cache/pypoetry/virtualenvs/pygreet-abcd1234-py3.8/bin/activate
(pygreet-abcd1234-py3.8) [pygreet]$ python
>>> from greet.location import greet
>>>

from greet.location import greet

def test_greet():
    result = greet("America/New_York")
    assert "New York!" in result

"""Send greetings."""

import arrow

import sys


def greet(tz):
    """Greet a location."""
    now = arrow.now(tz)
    friendly_time = now.format("h:mm a")
    location = tz.split("/")[-1].replace("_"," ")
    return f"Hello, {location}! The time is {friendly_time}."


def cli(args=None):
    """Process command line arguments."""
    if not args:
        args = sys.argv[1:]
    tz = args[0]
    print(greet(tz))

[tool.poetry.scripts]
greet = "greet.location:cli"

poetry install

poetry shell

(pygreet-abcd1234-py3.8) $ greet Africa/Addis_Ababa
Hello, Addis Ababa! The time is 1:49 pm.

poetry run greet Africa/Addis_Ababa

from greet.location import cli


def test_greet_cli(capsys):
    args = ["America/Argentina/San_Juan"]
    cli(args)
    captured = capsys.readouterr()
    result = captured.out
    assert "San Juan!" in result

poetry run pytest

import subprocess

def test_greet_cli2():
    result = subprocess.run(["greet", "America/Costa_Rica"], capture_output=True)
    assert b"Costa Rica!" in result.stdout